### ISSUE TITLE
undefined method `encode_tuple'

### ISSUE THREAD

**Issue by nahurst** [EthWorks/ethereum.rb#169]
### Steps to reproduce

test.rb:
```
require 'ethereum'
client = Ethereum::HttpClient.new('http://localhost:8545')
contract = Ethereum::Contract.create(file: "Greeter.sol", client: client)
address = contract.deploy_and_wait()
puts contract.call.greet(['hello there'])
```

Greeter.sol
```
pragma solidity ^0.8.0;

contract Greeter {
    constructor() {}

    struct Hi {
      string greeting;
    }

    function greet(Hi memory hi) public pure returns (string memory) {
        return hi.greeting;
    }
}
```

Run:
```
bundle init
bundle add ethereum.rb
ruby test.rb
```

### Expected behavior
This works in ethers.js
```
let address = '...'; 
const Contract = await ethers.getContractFactory('Greeter'); 
const contract = await Contract.attach(address);
await contract.greet(['hello there']); // returns 'hello there'
```

### Actual behavior

When running the above:
```
Traceback (most recent call last):
	10: from test.rb:6:in `<main>'
	 9: from <path>/ethereum.rb-2.5/lib/ethereum/contract.rb:322:in `block (2 levels) in create_function_proxies'
	 8: from <path>/ethereum.rb-2.5/lib/ethereum/contract.rb:179:in `call'
	 7: from <path>/ethereum.rb-2.5/lib/ethereum/contract.rb:173:in `call_raw'
	 6: from <path>/ethereum.rb-2.5/lib/ethereum/contract.rb:169:in `call_args'
	 5: from <path>/ethereum.rb-2.5/lib/ethereum/contract.rb:165:in `call_payload'
	 4: from <path>/ethereum.rb-2.5/lib/ethereum/encoder.rb:93:in `encode_arguments'
	 3: from <path>/ethereum.rb-2.5/lib/ethereum/encoder.rb:93:in `with_index'
	 2: from <path>/ethereum.rb-2.5/lib/ethereum/encoder.rb:93:in `each'
	 1: from <path>/ethereum.rb-2.5/lib/ethereum/encoder.rb:94:in `block in encode_arguments'
<path>/ethereum.rb-2.5/lib/ethereum/encoder.rb:14:in `encode': undefined method `encode_tuple' for #<Ethereum::Encoder:0x00007fa9ee0f6f28> (NoMethodError)
Did you mean?  encode_bytes
```

### System configuration
**Ruby version**: ruby 2.6.5p114
**Solc version**: 0.8.9+commit.e5eed63a.Darwin.appleclang
**Parity version**: n/a
**OS**: macOS 11.6

**Comment by kurotaky** [comment]
@nahurst 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
