### ISSUE TITLE
When connected to Parity, the IPC client connection sometimes returns a JSON parse error

### ISSUE THREAD

**Issue by TimoSci** [EthWorks/ethereum.rb#27]
The below doesn't happen for every call. Sometimes the block number is returned correctly. I suspect it happens when the Parity returns an empty string.

```
client.block_number
JSON::ParserError: A JSON text must at least contain two octets!
	from /home/tfj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/json/common.rb:156:in `initialize'
	from /home/tfj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/json/common.rb:156:in `new'
	from /home/tfj/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/json/common.rb:156:in `parse'
	from /home/tfj/.rvm/gems/ruby-2.3.1/gems/ethereum-0.5.2/lib/ethereum/ipc_client.rb:32:in `block (2 levels) in <class:IpcClient>'
	from (irb):2
	from /home/tfj/.rvm/rubies/ruby-2.3.1/bin/irb:11:in `<main>'
```

**Comment by TimoSci** [comment]
resolved by using the latest release
