### ISSUE TITLE
JSON::ParserError: 765: unexpected token at ''

### ISSUE THREAD

**Issue by jlstr** [EthWorks/ethereum.rb#90]
Hello,

I'm trying to load a contract's method in the following manner:

```
client = Ethereum::HttpClient.new('https://rinkeby.infura.io/<API_KEY>')
contract = Ethereum::Contract.create(name: 'MyToken', address: '0x000', abi: Abi.to_json, client: client)
```
Apparently the above is ok because it gives me the proper contract methods (ERC20):
```
> contract.transact.methods
=> [:name, :symbol, :transfer, :set_prices, :approve, :total_supply, :transfer_from, :decimals, :sell_price, :standard, :balance_of, :buy_price, :buy, :allowance, :sell, :admin .... ]
```
But when I try to call one the methods I get:

```
> contract.transact.name
JSON::ParserError: 765: unexpected token at ''
	from (irb):9
```

Any ideas about what I could be doing wrong? @ToJen Maybe you could give me a hand here?

Thank in advance!

**Comment by TxHashAdmin** [comment]
@jlstr I'd be happy to check it out.  Can you please post a copy of your Abi?

**Comment by jlstr** [comment]
@TxHashAdmin Absolutely,

Here it is: https://gist.github.com/jlstr/251f9057e0dd58a0574aca6db0643c63

The first file is the original JSON file. The second ruby file is the one I am converting into a JSON String.

Thank you very much!

**Comment by imthatcarlos** [comment]
looks like we have similar issues, here's my abi: https://gist.github.com/imthatcarlos/9093a6d29b21539338d0be971351ab92

and my stacktrace 
```
contract.transact.set_competition_admin('0x46AC3404a54B3Eaf8d3EA687a87EaC3BBfb1bd40')

/Users/carlos/.rbenv/versions/2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/Users/carlos/.rbenv/versions/2.5.1/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/Users/carlos/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ethereum.rb-2.2/lib/ethereum/client.rb:126:in `send_command'
/Users/carlos/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ethereum.rb-2.2/lib/ethereum/client.rb:137:in `block (2 levels) in <class:Client>'
/Users/carlos/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ethereum.rb-2.2/lib/ethereum/contract.rb:118:in `send_transaction'
/Users/carlos/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ethereum.rb-2.2/lib/ethereum/contract.rb:192:in `transact'
/Users/carlos/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ethereum.rb-2.2/lib/ethereum/contract.rb:324:in `block (2 levels) in create_function_proxies'
```

**Comment by imthatcarlos** [comment]
btw - I only get this full stack trace when I do something like 
```
def call_transaction
  contract.call.owner
rescue Exception => e
  puts "#{e.class}: #{e.message}"
  puts e.backtrace.join("\n")
end

**Comment by jlstr** [comment]
Thanks for the contribution @imthatcarlos! Passing a JSON String should be the number 1 option for getting a Reference to a Contract, I wish they would move forward solving this issue.

**Comment by longhoangwkm** [comment]
Does anyone resolved this issue ?!.  I got it too

**Comment by kceb** [comment]
Getting this too..

**Comment by Avdhesh51000** [comment]
How we can pass private key of address when calling contract method on testnet

**Comment by longhoangwkm** [comment]
@Avdhesh51000 
Here are my sample code. You can take a look to implement yourself

```ruby
class EthereumClient
  ETHEREUM_NETWORK_URL = ENV.fetch('ETHEREUM_NETWORK_URL')

  def self.client
    return @client if @client
    @client = Ethereum::HttpClient.new(ETHEREUM_NETWORK_URL)
    @client.default_account = SystemWallet.address
    @client
  end
end

class SmartContract
  attr_accessor :contract_instance
  ENCODER = Ethereum::Encoder.new

  def initialize(name, address, code, abi)
    @contract_instance = Ethereum::Contract.create(
      name: name,
      address: address,
      code: code,
      abi: abi,
      client: EthereumClient.client
    )
  end

  def contract_name
    @contract_instance.call.name
  end

  def contract_owner
    ENCODER.ensure_prefix(@contract_instance.call.owner)
  end

  def event_transfer_abi
    @contract_instance.abi.find { |abi| abi['name'] == 'Transfer' }
  end

  def event_signature(event_name)
    @contract_instance.parent.events.find { |e| e.name.to_s == event_name }.signature
  end

  def transfer_event_signature
    event_signature('Transfer')
  end

  def token_balance(address)
    @contract_instance.call.balance_of(address)
  end

  def transfer(from_private_hex, to_address, amount, fastest_fee = false)
    key = Eth::Key.new priv: from_private_hex
    @contract_instance.key = key
    @contract_instance.transact.transfer__address__uint256(to_address, amount)
  end
end
```

**Comment by kurotaky** [comment]
@jlstr 
Thanks for the issue. Please migrate as we will maintain the [eth.rb](https://github.com/q9f/eth.rb/) library here. ;)
